### PR TITLE
Fix 'typical' typo

### PR DESCRIPTION
**Pull request by coliff**
Fix typical typo

### CODE REVIEW

**Comment by rxaviers** [comment]
Thanks, just let me know when you sign CLA. The above label won't update automatically.

**Comment by coliff** [comment]
I just signed the CLA (sorry - thought I'd signed it before).

**Comment by rxaviers** [comment]
Thanks

**Comment by rxaviers** [comment]
Please, use the same name and last name on your commit message that you have signed.

**Comment by coliff** [comment]
Christian Oliff

**Comment by arthurvr** [comment]
The problem here is that the commit's author name is set as `Christian`, without a last name. By amending the commit with the `--author` flag you're able to change that.

**Comment by rxaviers** [comment]
@coliff when you amend your commit, you could force push it (`git push origin +patch-1`). Then, add a new comment so we get notified. Thanks

**Comment by rxaviers** [comment]
@coliff thanks for your help

**Comment by coliff** [comment]
@rxaviers Cool. Thanks for fixing and sorry I didn't amend my previous PR as requested - I don't use Git/Github via command line and wasn't sure how to do that force push.

**Pull request closed without merging**
