### PR TITLE
Globalize:Provide Bidi structured text support to MessageFormat #539

### PR DESCRIPTION
**Pull request by ashensis**
As per discussion in https://github.com/jquery/globalize/issues/539#issuecomment-149295018 
this PR is based on corresponding feature been recently introduced in SlexAxton/messageFormatter.js
(see https://github.com/SlexAxton/messageformat.js/pull/129)
It provides an ability to enforce Bidi structured text in message being formatted  by using Unicode Bidi control characters. The upgrading qualities are:

-     Prevents intermingling of text contained in placeholders with the rest of message text.
-     Maintains the integrity of Bidi text flowing according to directionality of language script. For reference to Bidi structured text see: http://cldr.unicode.org/development/development-process/design-proposals/bidi-handling-of-structured-text

### CODE REVIEW

**Comment by tomerm** [comment]
@rxaviers after contribution to SlexAxton/messageformat.js we are back to Globalize to finalize this task. Can you please review this submission ?  I would also appreciate your guidance on CLA error we currently experience with this PR. Thanks a lot in advance.

**Comment by jzaefferer** [comment]
It looks like you've filed this against the wrong repository. Even if this is on purpose, its definitely very wrong in some other way.

**Comment by jzaefferer** [comment]
This commit looks fine: c48e22bb42886edbebedc5601facc63867cdc107 - everything else doesn't belong here. Please create a new PR with only relevant commits.

**Comment by ashensis** [comment]
Hi @jzaefferer . I got somewhat confused, excuse me for ignorance. 
I created this PR basing on branch MF539 in my fork.
When you  say "everything else doesn't belong here", what do you mean by ELSE? 
To my humble understanding there is nothing else in my branch MF539 that had been created yesterday, apparently I am missing some point?
I didn't understand your comment about wrong repository either, what was wrong about all this?

**Comment by ashensis** [comment]
I see this creepy title
"ashensis wants to merge 813 commits into jquery:master from ashensis:MF539" but I have no idea where this 813 commits came from to my branch. May be I missed some crutial synchronization step?

**Comment by jzaefferer** [comment]
It seems like you branched [globalize/globalize](https://github.com/globalize/globalize) instead of jquery/globalize (this repo), then added a commit on top.

**Comment by ashensis** [comment]
Thank you , yes, I confess doing this once upon a time on my master branch by mistake, so I would kindly ask your advice, should this pattern work for me?:
git checkout master
git pull upstream master
$ git reset --hard upstream/master 
(I already did this on my master branch to get synchronized with upstream repository)
$ git checkout <this branch>
$ git rebase master
Should this work for getting read of all that mess?

**Comment by ashensis** [comment]
$ git checkout  (my branch name) - I missed this in next from last line

**Comment by rxaviers** [comment]
Considering `upstream` is the name you give for this repo, you could `git rebase -i upstream/master` inside your branch and leave the commits you have implemented only (discard the ones unrelated to this branch). Alternatively, you could `git checkout upstram/master && git checkout -b my-new-branch && git cherry-pick <commit-1> <commit-2> ...`, where commit-1, commit-2, etc are the ones you've implemented. Then, you push that new branch and create a PR on top of that. I hope that helps.

**Comment by ashensis** [comment]
Thank you, I created new PR https://github.com/jquery/globalize/pull/599 instead of this one

**Comment by rxaviers** [comment]
:+1:

**Pull request closed without merging**
