### PR TITLE
workaround for exception when globalize code is uglified

### PR DESCRIPTION
**Pull request by hippich**
#582

### CODE REVIEW

**Comment by rxaviers** [comment]
Thank you @hippich for finding this issue and providing a fix. I've left a couple of comments above, but overall it looks good to me.

**Comment by rxaviers** [comment]
That was quick, thanks

**Comment by hippich** [comment]
:) thanks for spotting it. IE comment wasn't supposed to be deleted :)

**Comment by rxaviers** [comment]
Thank you very much, landed.

**Pull request closed without merging**
