### PR TITLE
Update es.json

### PR DESCRIPTION
**Pull request by isaacdurazo**
@rxaviers how does this look?

### CODE REVIEW

**Comment by rxaviers** [comment]
Looks great! Thank you.

**Comment by rxaviers** [comment]
I just need you to read and sign the jQuery CLA:
http://contribute.jquery.org/CLA/status/?repo=globalize&sha=881248ab97b4e042faa332fa6656241d3216e7fd

**Comment by isaacdurazo** [comment]
All set @rxaviers

**Comment by rxaviers** [comment]
Awesome, thanks

**Comment by rxaviers** [comment]
Merged into #464

**Pull request closed without merging**
