### PR TITLE
Examples: Include unit formatting

### PR DESCRIPTION
**Pull request by rxaviers**
WIP PR for updating examples to include unit formatting.

Ref #252
Ref #254
Ref #512

### CODE REVIEW

**Comment by rxaviers** [comment]
@jzaefferer, @isaacdurazo, @markelog, @sompylasar, @AhmedMustafa,  we're adding support for Unit Formatting and consequently the demo has:

- One new message:
```diff
+		"unit-label": "Unit",
```
- One updated message:
```diff
-		"message-1": "An example of a message using mixed numbers \"{number}\", currencies \"{currency}\", dates \"{date}\", and relative time \"{relativeTime}\".",
+		"message-1": "An example of a message using mixed number \"{number}\", currency \"{currency}\", date \"{date}\", relative time \"{relativeTime}\", and unit \"{unit}\".",
```

Currently, English is being used to fill the gap for the following languages:
- [Arabic](https://github.com/jquery/globalize/pull/541/files#diff-e20fcb04b0c2f92ab8c21addd9697097)
- [German](https://github.com/jquery/globalize/pull/541/files#diff-77cb508bf0d77c7941569c5034636b45)
- [Spanish](https://github.com/jquery/globalize/pull/541/files#diff-c0dd4cc6823109783593fd7c63cb8005)
- [Russian](https://github.com/jquery/globalize/pull/541/files#diff-4e810c616cff5b308092fc8ec2df66c8)
- [Chinese](https://github.com/jquery/globalize/pull/541/files#diff-fac07625adf53b53686de77a20f82608)

If you find some time could you please provide an update (either by sending a PR or by replying in a new comment)?

Your continued help is very much appreciated. Thanks.

**Comment by AhmedMustafa** [comment]
@rxaviers  "unit" means unit of measurements like kilogram, metre, second, kelvin,...etc ?

**Comment by rxaviers** [comment]
> @rxaviers "unit" means unit of measurements like kilogram, metre, second, kelvin,...etc ?

Correct

**Comment by sompylasar** [comment]
Russian:
```
"unit-label": "Единица измерения",
"message-1": "Пример сообщения с числом \"{number}\", валютой \"{currency}\", датой \"{date}\", относительным временем \"{relativeTime}\" и единицей измерения \"{unit}\".",
```
I've rephrased the original "message-1" a bit.

**Comment by AhmedMustafa** [comment]
Arabic:
"unit-label": "وحدة القياس",
"message-1": "مثال علي رسالة باستخدام رقم مختلط \"{number}\", عملة \"{currency}\", تاريخ \"{date}\", وقت نسبي \"{relativeTime}\", و وحدة قياس \"{unit}\" ."

**Comment by rxaviers** [comment]
Thank you @AhmedMustafa and @sompylasar

**Comment by rxaviers** [comment]
Updated this PR

**Comment by rxaviers** [comment]
@jzaefferer please could you push a commit with translation for German? (baseline https://github.com/jquery/globalize/commit/34787ec0ce66f5f3aba8cf8f8b6e46bb9d2880d4)

**Comment by jzaefferer** [comment]
Done.

**Comment by rxaviers** [comment]
Awesome thanks.

**Pull request closed without merging**
