### PR TITLE
Various: Drop support for IE8

### LINKED ISSUE #571: Drop IE8 support
Currently, IE8 support means two things:
- In the docs, we have instructions for the inclusion of ES5 polyfill in such case;
- In the tests, we have a special trigger for IE8 that uses ES5 polyfill;

We could drop these by dropping support for IE8.

### PR DESCRIPTION
**Pull request by rxaviers**
Ref #561
Fixes #571

### CODE REVIEW

**Comment by rxaviers** [comment]
We can't simply remove `test/functional-es5-shim.html` file due to QUnit/phantomjs ([link](https://github.com/jquery/globalize/blob/7ff48e3cc92f539c894ec7fd79dd7b2e0e353ecd/Gruntfile.js#L105-L107)). @jzaefferer, it seems like there's a phantomjs2 ([source](https://github.com/ariya/phantomjs/tree/2.0.0)), any updates on QUnit supporting it? Thanks

**Comment by Arkni** [comment]
Maybe you also need to remove `es5-shim` from `bower.json`.

**Comment by rxaviers** [comment]
> Maybe you also need to remove `es5-shim` from `bower.json`.

That was also my original idea, but can't right now due to https://github.com/jquery/globalize/blob/7ff48e3cc92f539c894ec7fd79dd7b2e0e353ecd/Gruntfile.js#L105-L107.

**Comment by Arkni** [comment]
Just checked their repo and they claim it's fixed in version `2.0`.
So an upgrade may be needed here.

**Comment by rxaviers** [comment]
Yeap, thanks, which is the question I made to @jzaefferer above :smile:

**Comment by Arkni** [comment]
Haha, didn't notice your above comment :sweat_smile:

**Comment by rxaviers** [comment]
:wink:

**Comment by jzaefferer** [comment]
Looks like phantomjs 2.0 is too buggy and 2.1 isn't done yet: https://github.com/gruntjs/grunt-lib-phantomjs/issues/74#issuecomment-148767838 and https://github.com/ariya/phantomjs/issues/12970 (2.0.1 won't happen). 2.1.0 might happen this month: https://github.com/ariya/phantomjs/issues/12970#issuecomment-169539354 

Once that is out, updating grunt-lib-phantomjs seems straight forward enough: https://github.com/gruntjs/grunt-lib-phantomjs/issues/74#issuecomment-156092326

Afterwards grunt-contrib-qunit could be updated accordingly...

**Comment by rxaviers** [comment]
Thanks @jzaefferer

**Comment by Arkni** [comment]
@rxaviers 
Just to let you now, the latest version of `grunt-contrib-qunit` (`v1.0.1`) uses `PhantomJS v2.1.1`.

**Comment by rxaviers** [comment]
Thanks @Arkni

**Pull request closed without merging**
