### PR TITLE
313: Code Output Placement

### LINKED ISSUE #313: Docs: Code output placement
Throughout the documentation, code output often follows a code for clarity. For example:

```javascript
Globalize.locale( "en" );
Globalize.formatDate( new Date( 2010, 10, 30, 17, 55 ), { datetime: "short" } );
// "11/30/10, 5:55 PM"
```

Jörn once suggested that such comments to be placed above the code instead.

We need to evaluate and make the change consistent across the documentation.

### PR DESCRIPTION
**Pull request by matachines**
This fixes the inconsistencies in the code output placement of the documentation as per the style rules decided in the corresponding issue.

Fixes #313

### CODE REVIEW

**Comment by jzaefferer** [comment]
Diff looks good to me.

**Comment by rxaviers** [comment]
Fantastic, thanks. Please, could you read and sign jQuery [CLA](http://contribute.jquery.org/CLA/)?

**Comment by rxaviers** [comment]
Please, can you
- [ ] Add `>` in an output of "doc/api/core/locale.md"
- [ ] Add `>` in an output of "doc/api/date/date-formatter.md" line 84.
- [ ] Add `>` in an output of "doc/api/number/number-parser.md" line 40.

**Comment by matachines** [comment]
Just signed and added the missing arrows!

**Comment by rxaviers** [comment]
:+1:

**Pull request closed without merging**
