### PR TITLE
Build: Enable automated crossbrowser testing, including PRs

### LINKED ISSUE #235: Testing automation
We want to test this in all supported browsers automatically. I'll look into creating a configuration file for `browserstack-runner` to see if that works here. Otherwise we can try it with TestSwarm.

### PR DESCRIPTION
**Pull request by jzaefferer**
Fixes #235

### CODE REVIEW

**Comment by jzaefferer** [comment]
This still isn't working properly. I can get runs to pass locally, but the last amend failed on Travis: https://travis-ci.org/jquery/globalize/builds/52004614

The error always involves "requirejs failed to load". It mostly happens for `unit.html`, but there's at least one `functional.html` failure as well. I wonder if increasing the requirejs `waitSeconds` option further would help. We've already changed it from the default 7 to 30.

**Comment by jzaefferer** [comment]
I've rebased this after #431 landed, but now it fails due to the commitplease:currentBranch task. I have no idea what's up with that, will wait for Rafael to fix that in master and try again. @rxaviers would be great if you could also run browserstack-runner locally (make sure to install at least 0.3.0).

**Comment by rxaviers** [comment]
I'm looking forward to having automated crossbrowser testing! :+1:

> I have no idea what's up with that

AFAICT, Travis clones the latest 50 commits only (for improved speed). Therefore, the commit range referenced by commitplease task is not available there.

If we can configure Travis to clone it up to the `--root`, this is a non-problem. By the way, cloning the whole repo in my Brazilian Internet connection takes 6s, which is very little compared to running `browserstack-runner` anyway.

> @rxaviers would be great if you could also run browserstack-runner locally (make sure to install at least 0.3.0).

Do you want me to test anything in particular in my local environment? Why do you want me to run it please?

**Comment by jzaefferer** [comment]
> If we can configure Travis to clone it up to the --root, this is a non-problem. By the way, cloning the whole repo in my Brazilian Internet connection takes 6s, which is very little compared to running browserstack-runner anyway.

Sounds good.

> Do you want me to test anything in particular in my local environment? Why do you want me to run it please?

Just to avoid a "its working on my machine!!!".

**Comment by rxaviers** [comment]
We'll need to update this according to #450 changes.

**Comment by rxaviers** [comment]
Closing in favor of #450

**Pull request closed without merging**
