### PR TITLE
Date: Create unit tests to verify day parsing uses the correct day range given its corresponding month/year

### LINKED ISSUE #323: parseDate: incorrect result when parsing last day of month
Hi, there seems to be a problem in date/parse.js with parsing a date which day part is greater than amount of days current month has and a day part is parsed before a month part.
Today it's 30.09.2014 and parsing "31.10.2014" would yield 30.10.2014. The reason it happens is that initial date is current date and for September 31.09.2014 is an incorrect date.

### PR DESCRIPTION
**Pull request by rxaviers**
Fixes #323
Ref #373

### CODE REVIEW

**Comment by jzaefferer** [comment]
Specifically the clock feature: http://sinonjs.org/docs/#clock

```js
var clock = sinon.useFakeTimers(now);
```

Where `now` is your custom "today" as a timestamp. That should do the trick.

**Comment by rxaviers** [comment]
Awesome. I've updated this PR to use Sinon.js instead of my custom implementation on tests.

**Comment by jzaefferer** [comment]
Looks good to me.

**Comment by rxaviers** [comment]
Testing this PR+Sinon.js across various browsers resulted in errors/failures (I've merged in the browserstack-runner branch locally to test it). Running browserstack-runner against my custom implementation passes just fine.

- Sinon.js on browserstack: [fail](https://gist.github.com/rxaviers/8f0ad35f478941f2da8d).
- Custom `FakeDate` on browserstack: [pass](https://gist.github.com/rxaviers/c028c0cff270b88061ad).

Potentially, the Sinon.js failures are only related to AMD loading, giving the fact some failing tests intermittently pass.

**Comment by rxaviers** [comment]
We could land this PR + Sinon.js now with no problem. But, it would impact (i.e. delay) testing automation #235 (i.e., to land browserstack-runner branch #367), since we would have to figure out what this failures were.

Giving test automation (which is due to 1.0.0) and #323 have higher priorities compared to using Sinon.js to simplify FakeDate here on tests, I'm considering to track that as a separate issue unless anyone has a different idea. So, we can land #373 (fixing #323), land browserstack-runner branch. Then, spend time on it.

What do you think?

**Comment by jzaefferer** [comment]
Is the sinon/browserstack failure consistent? Can you reproduce it when running the given browser manually?

If we're not getting anywhere, I'm okay with keeping `FakeDate` for now.

**Comment by rxaviers** [comment]
It's not consistent. I haven't tried it manually. The problem could be simple. But, it will require some time investigating. I just thing this time is best spent somewhere else now. :)

**Comment by jzaefferer** [comment]
Okay, let's give sinon another try later.

**Pull request closed without merging**
