### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mgenereu**
Fixed spelling error.

### CODE REVIEW

**Comment by rxaviers** [comment]
Hi @mgenereu, thanks for you contribution. But, this is already been addressed by https://github.com/jquery/globalize/tree/doc-fixes. If you have any other fixes though, I'm happy to look into.

Thanks

**Comment by mgenereu** [comment]
Nope.  Just trying to do my little part.  Did some contribute information reference that branch?

**Comment by rxaviers** [comment]
>  Did some contribute information reference that branch?

That branch is a short living dynamic one, whose purpose is to fix recent documentation bugs. I don't think it's being referenced anywhere except in the branch list. Did I answer your question? Just let me know if you still have questions...

**Comment by mgenereu** [comment]
That answers my question.  I thought I'd failed to read the docs on how to contribute.

**Comment by rxaviers** [comment]
Not your fault and thanks again.

**Pull request closed without merging**
